#!/usr/bin/env bash
# script transfers a file from our client to a server

i=3;
n=$#;
if [[ $n -lt $i ]];then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp ./$1 $3@$2:$4
fi