#!/usr/bin/env bash
# script transfers a file from our client to a server

i=3;
n=$#;
destination=$HOME
if [[ $n -lt $i ]];then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -o UserKnownHostsFile="$4" ./"$1" "$3"@"$2":"$destination"
fi
