#!/usr/bin/env bash
# script installs nginx on web server

sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
echo "Hello World!" | sudo tee '/var/www/html/index.nginx-debian.html'  > /dev/null
if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
