#!/usr/bin/env bash
# script installs nginx on web server

sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo systemctl start nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
