#!/usr/bin/env bash
# Configures your Nginx server so that /redirect_me is redirecting to another page.
sudo apt -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
echo "Hello World!" | sudo tee '/var/www/html/redirect_me.html'  > /dev/null
if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
new_string="location / {/nRedirect 301 / https://www.youtube.com/watch?v=QH2-TGUlwu4/;"
sudo sed -i "s|location / {|$new_string|g" /etc/nginx/sites-available/default
