#!/usr/bin/env bash
# Configures your Nginx server so that /redirect_me is redirecting to another page.
sudo apt -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
echo "Hello World!" | sudo tee '/var/www/html/redirect_me.html'  > /dev/null
new_string="location / {/nRedirect 301 /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/;"
sudo sed -i "s|location / {|$new_string|g" /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
