#!/usr/bin/env bash
# Configures  Nginx server to have a custom 404 page
sudo apt -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
echo "Hello World!" | sudo tee '/var/www/html/index.nginx-debian.html' > /dev/null
echo "Ceci n'est pas une page" | sudo tee '/var/www/html/404.html'  > /dev/null
current_string="server_name _;"
new_string="server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s|$current_string|$new_string|g" /etc/nginx/sites-available/default
sudo sed -i "s/^\t\}$/\t\}\n\n\terror_page 404 \/404.html;/" /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
