#!/usr/bin/env bash
# configures a brand new Ubuntu machine

sudo apt -y update
sudo apt -y upgrade

# installs nginx on web server
sudo apt-get -y install nginx

# enable nginx firewall
sudo ufw allow 'Nginx HTTP'
sudo ufw enable

# modify default pages
echo "Hello World!" | sudo tee '/var/www/html/index.nginx-debian.html'  > /dev/null
echo "Not found" > /usr/share/nginx/html/custom_404.html

# setup custom header on web server
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.buliro.net permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

# start nginx
service nginx start
