#!/usr/bin/env bash
# install load balancer

# colors
green='\e[1;32m'
blue='\e[1;34m'
yellow='\e[1;33;1;40m'
reset='\033[0m'

echo -e "${blue}Running updates and checks...${reset}\n"

function install() {
	command -v "$1" &> /dev/null

	#shellcheck disable=SC2181
	if [ $? -ne 0 ]; then
		echo -e "Installing: ${yellow}$1${reset}\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "${yellow}${1} is already installed.${reset}\n"
	fi
}

install haproxy #install haproxy

echo -e "${green}Finishing up.${reset}\n"

sudo cp /etc/haproxy/haproxy.cfg haproxy_cfg.backup

server_config=\
"
global
	    maxconn 1000
  		log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
		log global
		mode http
  		option forwardfor
        option  httplog
        option  dontlognull
  		timeout connect 5000
  		timeout client 50000
  		timeout server 50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend www
    	bind *:80
    	default_backend webservers

backend webservers
    	balance roundrobin
    	server 100910-web-01 34.204.95.189:80 check
    	server 100910-web-02 54.236.44.63:80 check
"

# shellcheck disable=SC2154
#echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg
echo "$server_config" | sudo tee '/etc/haproxy/haproxy.cfg' > /dev/null

# enable haproxy to be started by init script
#echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy
echo "ENABLED=1" | sudo tee '/etc/default/haproxy' > /dev/null

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
