#!/usr/bin/env bash
# Configures ufw firewall to
# allow all outgoing traffic and
# block all incoming traffic except for ports 22(SSH), 443(HTTPS) and 80(HTTP).

sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
